(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
function capture(event,props={}){try{if(localStorage.getItem('atlasAnalyticsOptOut')==='1')return;if(window.posthog?.capture)window.posthog.capture(event,props)}catch(_){}}
function openCore(view){const b=$(`[data-view="${view}"]`);if(b)b.click()}
function openPlus(id){$$('.view').forEach(v=>v.classList.remove('active'));$$('.navbtn').forEach(b=>b.classList.remove('active'));const v=$(`#view-${id}`);if(v){v.classList.add('active');history.replaceState(null,'',`#${id}`);window.scrollTo({top:0,behavior:'instant'});capture('atlas_view',{view:id})}$('#mobileNav')?.classList.remove('open');$('#menuBtn')?.setAttribute('aria-expanded','false')}
function search(q){openCore('library');setTimeout(()=>{const i=$('#searchInput');if(!i)return;i.value=q;i.dispatchEvent(new Event('input',{bubbles:true}));capture('search',{query_length:q.length,source:'discovery_layer'});},40)}
function style(){const s=document.createElement('style');s.textContent=`
.atlas-plus-tabs{display:flex;gap:4px}.atlas-plus-card{background:#fff;border:1px solid var(--line);border-radius:18px;padding:18px;text-align:left}.atlas-plus-card h3{margin:7px 0 5px}.atlas-plus-card p{margin:0;color:var(--muted);font-size:13px}.atlas-plus-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.atlas-plus-grid.two{grid-template-columns:repeat(2,1fr)}.atlas-plus-hero{margin:26px 0 20px;border-radius:26px;padding:36px;background:linear-gradient(135deg,#0b1020,#172554);color:#fff}.atlas-plus-hero h1{font-size:clamp(34px,5vw,58px);line-height:1.03;letter-spacing:-.045em;margin:8px 0}.atlas-plus-hero p{color:#dbeafe;max-width:760px}.stack{background:#fff;border:1px solid var(--line);border-radius:20px;padding:20px}.stack h3{margin:0 0 4px}.stack-goal{color:var(--muted);margin:0 0 14px}.stack-steps{margin:12px 0;padding-left:20px}.stack-tools{display:flex;flex-wrap:wrap;gap:6px;margin:10px 0}.stack-tools span{background:#eef4ff;color:#1849a9;padding:5px 8px;border-radius:999px;font-size:12px;font-weight:700}.choice-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:12px}.choice{border:1px solid var(--line);border-radius:12px;padding:10px;font-size:12px}.choice b{display:block}.feedbackbar{position:relative;margin:28px 0 10px;border:1px solid var(--line);border-radius:18px;background:#fff;padding:16px;display:flex;gap:10px;align-items:center;flex-wrap:wrap}.feedbackbar strong{margin-right:auto}.unmet{display:flex;gap:8px;width:100%}.unmet input{flex:1;min-width:0;border:1px solid #d0d5dd;border-radius:10px;padding:10px 12px;font:inherit}.micro{font-size:12px;color:var(--muted)}
@media(max-width:1000px){.atlas-plus-grid{grid-template-columns:repeat(2,1fr)}.choice-grid{grid-template-columns:repeat(2,1fr)}}
@media(max-width:680px){.atlas-plus-grid,.atlas-plus-grid.two,.choice-grid{grid-template-columns:1fr}.atlas-plus-hero{padding:28px 22px;border-radius:20px}.atlas-plus-card,.stack{padding:16px}.unmet{display:grid}.feedbackbar .btn{min-height:44px}.atlas-plus-card{min-height:44px}.nav{overflow:hidden}}
`;document.head.appendChild(s)}
const DO=[
['AI & Automation','Agents, models, workflows and automations','AI agent automation workflow'],['Build & Make Money','Websites, sales, marketing and monetization','website marketing sales business'],['Creator Studio','Video, voice, images, editing and publishing','video voice image creator'],['Build Something','Code, apps, prototypes and websites','coding app website developer'],['Research & Intelligence','Deep research, papers, source discovery and analysis','research academic intelligence'],['Coach & Fitness Business','Client intake, programming, delivery and follow-up','fitness coaching business client'],['Grants / Maps / GIS','Grant research, mapping, geospatial and public data','grant GIS mapping geospatial'],['Markets & Trading Tools','Charts, market data, screeners and risk tools','trading market chart risk'],['Local Intelligence','Local data, maps, government and community research','local maps government data'],['Utilities','PDF, OCR, converters, calculators and everyday tools','pdf ocr converter utility']];
const LEARN=[['AI','AI courses tutorials reference'],['Coding / Python','learn Python coding course'],['Business / Marketing','business marketing course tutorial'],['Fitness science','fitness exercise science research'],['Math / Science','math science education'],['History / Languages','history language learning'],['Tutorials / Courses / Reference','tutorial course reference education']];
const EXPLORE=[['I’m bored','interesting weird fun useful sites'],['Show me something cool','visual interactive experiment'],['Weird internet','weird internet sites'],['Maps','interactive map earth'],['Games','browser games free'],['Visual experiments','interactive visualization experiment'],['Useful random sites','useful tools random'],['Live cams','live nature cams'],['Science / space','space science NASA']];
const STACKS=[
{id:'reel',name:'Make a Reel',goal:'Create and publish a polished short-form video.',steps:['Draft the hook and script','Generate or record voice','Edit vertically with captions','Quality-check on mobile','Publish and measure'],tools:['ChatGPT','ElevenLabs','CapCut','Instagram / TikTok / YouTube'],easy:'ChatGPT → CapCut',free:'ChatGPT free tier + CapCut free',best:'ChatGPT → ElevenLabs → CapCut',mobile:'ChatGPT + CapCut mobile',alt:'Canva, Descript, Adobe Express'},
{id:'website',name:'Build a Website',goal:'Go from idea to a live site with analytics and payments.',steps:['Define offer and pages','Generate copy and structure','Build and host','Add analytics','Add checkout','Test mobile and conversion path'],tools:['ChatGPT','Wix / Replit / GitHub','PostHog','Stripe'],easy:'Wix',free:'GitHub Pages',best:'Replit or Wix + PostHog + Stripe',mobile:'Wix mobile management',alt:'Framer, Webflow, Cloudflare Pages'},
{id:'agent',name:'Create AI Agent',goal:'Build a reliable tool-using AI workflow.',steps:['Pick model','Define tools and permissions','Add router / orchestration','Deploy endpoint','Add logging and health checks','Red-team failure cases'],tools:['OpenAI / model','Tool connectors','Router','Cloudflare / Replit','Monitoring'],easy:'Single model + a few tools',free:'Open-source model + free hosting tiers',best:'Model router + explicit tool schemas + monitoring',mobile:'Web control surface',alt:'Qwen, Hermes, OpenRouter'},
{id:'fitness',name:'New Fitness Client',goal:'Turn a lead into a coached client with a repeatable delivery system.',steps:['Lead capture','Intake and readiness screen','Assessment','Schedule','Program','Deliver sessions','Weekly follow-up and progression'],tools:['Forms','Calendar','Programming system','Notion / Docs','Messaging'],easy:'Form → Calendar → shared plan',free:'Google Forms + Calendar + Docs',best:'CRM + intake + program + automated follow-up',mobile:'Forms + Calendar + shared doc',alt:'Trainerize, TrueCoach, Airtable'},
{id:'grant',name:'Research a Grant',goal:'Move from funding opportunity to defensible submission materials.',steps:['Find official source','Confirm eligibility and dates','Collect evidence','Map geography / GIS','Draft documents','QA citations and requirements','Package submission'],tools:['Official grant portal','Research tools','GIS','Docs','QA checklist'],easy:'Official source + structured research doc',free:'Government portals + QGIS + Docs',best:'Source log + GIS + document QA workflow',mobile:'Research / review on mobile; GIS on desktop',alt:'ArcGIS, QGIS, Google Earth'}
];
function page(id,kicker,title,desc,body){return `<section class="view" id="view-${id}"><div class="atlas-plus-hero"><div class="eyebrow">${kicker}</div><h1>${title}</h1><p>${desc}</p></div>${body}<div class="feedbackbar" data-feedback-scope="${id}"><strong>Was this useful?</strong><button class="btn outline" data-feedback="yes">Yes</button><button class="btn outline" data-feedback="no">No</button><div class="unmet"><input aria-label="Tell Atlas what you could not find" placeholder="I couldn’t find what I needed…"><button class="btn blue" data-unmet>Send</button></div><span class="micro">Feedback improves discovery; it does not affect verification or organic ranking.</span></div></section>`}
function cards(items,source){return `<div class="atlas-plus-grid">${items.map(([n,d,q])=>`<button class="atlas-plus-card" data-q="${q||n}" data-source="${source}"><h3>${n}</h3>${d?`<p>${d}</p>`:''}</button>`).join('')}</div>`}
function stackHTML(s){return `<article class="stack"><div class="eyebrow" style="color:#175cd3">Complete workflow</div><h3>${s.name}</h3><p class="stack-goal">${s.goal}</p><ol class="stack-steps">${s.steps.map(x=>`<li>${x}</li>`).join('')}</ol><div class="stack-tools">${s.tools.map(x=>`<span>${x}</span>`).join('')}</div><div class="choice-grid"><div class="choice"><b>Easiest</b>${s.easy}</div><div class="choice"><b>Free option</b>${s.free}</div><div class="choice"><b>Best overall</b>${s.best}</div><div class="choice"><b>Mobile-friendly</b>${s.mobile}</div></div><p class="micro"><b>Alternatives:</b> ${s.alt}. Tools are shown because each fills a distinct step in the workflow; pricing/access still follow Atlas’s audited metadata rather than these workflow labels.</p><button class="btn soft" data-stack-search="${s.name}">Find tools for this Stack</button></article>`}
function inject(){style();const main=$('#main');if(!main)return;
 const doPage=page('do','DO','Accomplish something','Start from the outcome. Atlas will route you into the existing intent-ranked library instead of forcing you to know a tool name.',cards(DO,'do'));
 const learnPage=page('learn','LEARN','Learn something','Find tutorials, courses, reference material and research by subject.',cards(LEARN.map(([n,q])=>[n,'',q]),'learn'));
 const exploreBody=`<div class="sectionhead"><div><h2>Explore by mood</h2><p>Useful discovery for when you do not know what you want yet.</p></div><button class="btn blue" id="surprisePlus">Surprise Me</button></div>${cards(EXPLORE.map(([n,q])=>[n,'',q]),'explore')}`;
 const explorePage=page('explore','EXPLORE','Discover something useful','Bored, curious, or looking for something unexpected? Use a mood or let Atlas choose.',exploreBody);
 const stacksPage=page('stacks','STACKS','Complete workflows, not isolated tools','Each Stack starts with a goal, shows the sequence, and gives easiest, free, best-overall, mobile-friendly and alternate paths.',`<div class="atlas-plus-grid two">${STACKS.map(stackHTML).join('')}</div>`);
 main.insertAdjacentHTML('beforeend',doPage+learnPage+explorePage+stacksPage);
 const nav=$('.navlinks');if(nav){[['do','Do'],['learn','Learn'],['stacks','Stacks'],['explore','Explore']].forEach(([id,label])=>{const b=document.createElement('button');b.className='navbtn atlas-plus-nav';b.dataset.plusView=id;b.textContent=label;nav.prepend(b)})}
 const mobile=$('#mobileNav');if(mobile){[['do','Do'],['learn','Learn'],['stacks','Stacks'],['explore','Explore']].forEach(([id,label])=>{const b=document.createElement('button');b.className='navbtn';b.dataset.plusView=id;b.textContent=label;mobile.prepend(b)})}
 document.addEventListener('click',e=>{const pv=e.target.closest('[data-plus-view]');if(pv){openPlus(pv.dataset.plusView);return}const c=e.target.closest('[data-q]');if(c){capture('intent submitted',{surface:c.dataset.source||'discovery',intent:c.textContent.trim().slice(0,80)});search(c.dataset.q);return}const ss=e.target.closest('[data-stack-search]');if(ss){capture('stack opened',{stack:ss.dataset.stackSearch});search(ss.dataset.stackSearch);return}const f=e.target.closest('[data-feedback]');if(f){const scope=f.closest('[data-feedback-scope]')?.dataset.feedbackScope||'unknown';capture('feedback '+f.dataset.feedback,{scope});f.closest('.feedbackbar').querySelector('strong').textContent='Thanks — feedback recorded.';return}const u=e.target.closest('[data-unmet]');if(u){const bar=u.closest('.feedbackbar'),input=bar.querySelector('input'),value=input.value.trim();if(!value)return;capture('unmet request',{scope:bar.dataset.feedbackScope,length:value.length});input.value='';bar.querySelector('strong').textContent='Request recorded.';return}const tool=e.target.closest('[data-tool-visit]');if(tool)capture('outbound click',{tool_id:tool.dataset.toolId,domain:tool.dataset.toolDomain});const detail=e.target.closest('button[onclick^="openDetail"]');if(detail)capture('result opened',{});const fav=e.target.closest('.fav');if(fav)capture('saved',{});});
 $('#surprisePlus')?.addEventListener('click',()=>{const picks=['live nature cams','NASA space science','interactive maps','visual experiments','free documentaries','weird useful websites','browser games','learn something random'];const q=picks[Math.floor(Math.random()*picks.length)];capture('surprise used',{query:q});search(q)});
 const watchBtn=$('[data-view="watch"]');watchBtn?.addEventListener('click',()=>capture('watch opened',{}),true);
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#mobileNav')?.classList.contains('open')){$('#mobileNav').classList.remove('open');$('#menuBtn')?.setAttribute('aria-expanded','false')}});
 if(['do','learn','stacks','explore'].includes(location.hash.slice(1)))openPlus(location.hash.slice(1));
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject,{once:true});else inject();
})();