(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
function capture(event,props={}){try{if(window.atlasStorage.getItem('atlasAnalyticsOptOut')==='1')return;if(window.posthog?.capture)window.posthog.capture(event,{atlas_discovery_version:'5.0',...props})}catch(_){}}
function openCore(view){const b=$(`[data-view="${view}"]`);if(b)b.click()}
function openPlus(id){window.Atlas.navigate(id)}
const BEHAVIOR_POLICY={enabled:false,min_searches_per_intent:25,min_result_opens_per_candidate:5,min_distinct_sessions:10,max_rank_bonus:8,reason:'Insufficient attributable production usage. Behavior signals may never override verification, access, dead/parked guards, or explicit task fit.'};
function familyFrom(q=''){const n=q.toLowerCase();if(/grant|funding/.test(n))return'grants';if(/gis|map|geospatial|terrain/.test(n))return'gis_maps';if(/fitness|workout|coach|client/.test(n))return'fitness_coaching';if(/trade|market|stock|crypto|risk/.test(n))return'markets';if(/video|reel|creator|voice|podcast/.test(n))return'creator';if(/website|landing|seo|sales|marketing|money/.test(n))return'business_build';if(/agent|automation|workflow|code|python/.test(n))return'ai_automation';if(/movie|watch|stream|cam|nasa/.test(n))return'watch_listen';if(/learn|course|tutorial|research|paper/.test(n))return'learn_research';return'general';}
function search(q,meta={}){window.Atlas.search(q);capture('atlas_discovery_search',{task_family:meta.task_family||familyFrom(q),source:meta.source||'discovery',query_length:q.length})}
function style(){const s=document.createElement('style');s.textContent=`
.atlas-plus-card{background:#fff;border:1px solid var(--line);border-radius:18px;padding:18px;text-align:left;min-height:128px}.atlas-plus-card h3{margin:7px 0 5px}.atlas-plus-card p{margin:0;color:var(--muted);font-size:13px}.atlas-plus-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.atlas-plus-grid.two{grid-template-columns:repeat(2,1fr)}.atlas-plus-hero{margin:26px 0 20px;border-radius:26px;padding:36px;background:linear-gradient(135deg,#0b1020,#172554);color:#fff}.atlas-plus-hero h1{font-size:clamp(34px,5vw,58px);line-height:1.03;letter-spacing:-.045em;margin:8px 0}.atlas-plus-hero p{color:#dbeafe;max-width:760px}.stack{background:#fff;border:1px solid var(--line);border-radius:20px;padding:20px}.stack h3{margin:0 0 4px}.stack-goal{color:var(--muted);margin:0 0 14px}.stack-steps{margin:12px 0;padding-left:20px}.stack-tools{display:flex;flex-wrap:wrap;gap:6px;margin:10px 0}.stack-tools span{background:#eef4ff;color:#1849a9;padding:5px 8px;border-radius:999px;font-size:12px;font-weight:700}.choice-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:12px}.choice{border:1px solid var(--line);border-radius:12px;padding:10px;font-size:12px}.choice b{display:block}.feedbackbar{position:relative;margin:28px 0 10px;border:1px solid var(--line);border-radius:18px;background:#fff;padding:16px;display:flex;gap:10px;align-items:center;flex-wrap:wrap}.feedbackbar strong{margin-right:auto}.unmet{display:flex;gap:8px;width:100%}.unmet input{flex:1;min-width:0;border:1px solid #d0d5dd;border-radius:10px;padding:10px 12px;font:inherit}.micro{font-size:12px;color:var(--muted)}.playbook{background:#fff;border:1px solid var(--line);border-radius:18px;padding:18px;display:flex;flex-direction:column;gap:10px}.playbook h3{margin:0}.playbook pre{white-space:pre-wrap;font:12px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace;background:#f8fafc;border:1px solid var(--line);padding:12px;border-radius:12px;max-height:180px;overflow:auto}.playbook-meta{display:flex;gap:6px;flex-wrap:wrap}.playbook-meta span{font-size:11px;background:#f2f4f7;border-radius:999px;padding:4px 7px}.evidence-note{background:#fffaeb;border:1px solid #fedf89;border-radius:16px;padding:15px 17px;margin:0 0 18px}.evidence-note b{display:block}.filterline{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:0 0 16px}.filterline input,.filterline select{border:1px solid #d0d5dd;background:#fff;border-radius:10px;padding:10px 12px;font:inherit}.filterline input{flex:1;min-width:220px}
@media(max-width:1000px){.atlas-plus-grid{grid-template-columns:repeat(2,1fr)}.choice-grid{grid-template-columns:repeat(2,1fr)}}
@media(max-width:680px){.atlas-plus-grid,.atlas-plus-grid.two,.choice-grid{grid-template-columns:1fr}.atlas-plus-hero{padding:28px 22px;border-radius:20px}.atlas-plus-card,.stack,.playbook{padding:16px}.unmet{display:grid}.feedbackbar .btn,.atlas-plus-card,.playbook .btn{min-height:44px}.filterline{display:grid}.filterline input,.filterline select{width:100%;min-width:0}.nav{overflow:hidden}}
`;document.head.appendChild(s)}
const DO=[
['AI & Automation','Agents, models, workflows and automations','AI agent automation workflow'],['Build & Make Money','Websites, sales, marketing and monetization','website marketing sales lead generation'],['Creator Studio','Video, voice, images, editing and publishing','video voice image creator editor'],['Build Something','Code, apps, prototypes and websites','coding app website developer'],['Research & Intelligence','Deep research, papers, source discovery and analysis','research academic intelligence'],['Coach & Fitness Business','Client intake, programming, delivery and follow-up','fitness coaching workout programming client'],['Grants / Maps / GIS','Grant research, mapping, geospatial and public data','grant GIS mapping geospatial funding'],['Markets & Trading Tools','Charts, market data, screeners and risk tools','trading market chart screener risk'],['Local Intelligence','Local data, maps, government and community research','local government public data maps'],['Utilities','PDF, OCR, converters, calculators and everyday tools','pdf ocr converter calculator utility']];
const LEARN=[['AI','AI courses tutorials reference'],['Coding / Python','learn Python coding course'],['Business / Marketing','business marketing course tutorial'],['Fitness science','fitness exercise science research'],['Math / Science','math science education'],['History / Languages','history language learning'],['Tutorials / Courses / Reference','tutorial course reference education']];
const EXPLORE=[['I’m bored','interesting weird fun useful sites'],['Show me something cool','visual interactive experiment'],['Weird internet','weird internet sites'],['Maps','interactive map earth'],['Games','browser games free'],['Visual experiments','interactive visualization experiment'],['Useful random sites','useful tools random'],['Live cams','live nature animal cams'],['Science / space','NASA space science streams']];
const FREE_PATH='Use Atlas “Actually Free / No Login” filters at each step; only audited access labels count.';
const STACKS=[
{id:'reel',name:'Make a Reel',family:'creator',goal:'Create and publish a polished short-form video.',steps:['Draft hook and script','Generate or record voice','Edit vertically with captions','Quality-check on mobile','Publish and measure'],tools:['Writing model','Voice tool','Vertical editor','Publishing platform'],easy:'Script → mobile editor → publish',free:FREE_PATH,best:'Script → voice → editor → publish → analytics',mobile:'Use mobile-capable writing, voice and editing tools',alt:'Canva, Descript, Adobe Express',q:'short social video editor AI voice'},
{id:'website',name:'Build a Website',family:'business_build',goal:'Go from offer to a live site with measurement and checkout.',steps:['Define offer and pages','Create copy and structure','Build and host','Add analytics','Add checkout','Test mobile conversion path'],tools:['AI writing','Site builder','Analytics','Payments'],easy:'Site builder with hosted publishing',free:FREE_PATH,best:'Builder + analytics + payments + QA',mobile:'Choose a builder with mobile management',alt:'Wix, Replit, GitHub Pages, Framer',q:'website builder analytics payment'},
{id:'agent',name:'Create AI Agent',family:'ai_automation',goal:'Build a reliable tool-using AI workflow.',steps:['Pick model','Define tools and permissions','Add routing','Deploy endpoint','Add logging and health checks','Red-team failures'],tools:['Model','Tool connectors','Router','Hosting','Monitoring'],easy:'One model + a few explicit tools',free:FREE_PATH,best:'Router + explicit schemas + monitoring',mobile:'Use a web control surface',alt:'OpenAI, Qwen, Hermes, OpenRouter',q:'AI agent automation workflow monitoring'},
{id:'fitness',name:'New Fitness Client',family:'fitness_coaching',goal:'Turn a lead into a repeatable coaching workflow.',steps:['Lead capture','Readiness and intake','Assessment','Schedule','Program','Deliver','Weekly progression follow-up'],tools:['Form','Calendar','Programming system','Shared plan','Messaging'],easy:'Form → calendar → shared plan',free:FREE_PATH,best:'CRM + intake + program + follow-up',mobile:'Forms + calendar + shared plan',alt:'Airtable, Trainerize, TrueCoach',q:'fitness coaching client intake workout programming'},
{id:'grant',name:'Research a Grant',family:'grants',goal:'Move from funding opportunity to defensible submission material.',steps:['Find official source','Confirm eligibility and dates','Collect evidence','Map geography','Draft documents','QA citations and requirements','Package submission'],tools:['Official portals','Research','GIS','Documents','QA checklist'],easy:'Official source + structured research doc',free:FREE_PATH,best:'Source log + GIS + document QA',mobile:'Research/review mobile; GIS desktop',alt:'Grants.gov, QGIS, ArcGIS, Google Earth',q:'grant funding research GIS mapping'},
{id:'podcast',name:'Produce a Podcast Episode',family:'creator',goal:'Research, record, edit and publish an episode.',steps:['Choose angle','Research and outline','Record','Clean audio','Create show notes','Publish and distribute'],tools:['Research','Recorder','Audio editor','Transcription','Podcast host'],easy:'Record → edit → host',free:FREE_PATH,best:'Research → record → edit → transcript → distribute',mobile:'Mobile recorder + editor + host',alt:'Descript, Audacity, Riverside',q:'podcast recording audio editor transcription'},
{id:'youtube',name:'Make a YouTube Video',family:'creator',goal:'Turn an idea into a researched, edited and measurable video.',steps:['Validate topic','Outline and script','Capture/generate assets','Edit','Thumbnail/title','Publish','Review analytics'],tools:['Research','Script','Video editor','Design','Analytics'],easy:'Script → editor → YouTube',free:FREE_PATH,best:'Research → script → edit → thumbnail → analytics',mobile:'Mobile editor + YouTube Studio',alt:'CapCut, DaVinci Resolve, Canva',q:'youtube video editor thumbnail research'},
{id:'newsletter',name:'Launch a Newsletter',family:'business_build',goal:'Build a repeatable newsletter from research to distribution.',steps:['Define audience','Collect sources','Draft issue','Edit','Send','Measure opens/clicks','Feed insights into next issue'],tools:['Research','Writing','Email platform','Analytics'],easy:'Draft → email platform',free:FREE_PATH,best:'Research pipeline + email + measurement',mobile:'Mobile-friendly email platform',alt:'Substack, Beehiiv, Mailchimp',q:'newsletter email marketing writing'},
{id:'landing',name:'Launch a Paid Offer',family:'business_build',goal:'Create a focused offer page with checkout and measurement.',steps:['Define customer/problem','Package offer','Write landing page','Build page','Connect payment','Add analytics','Test checkout and mobile'],tools:['Research','Copy','Landing builder','Payments','Analytics'],easy:'Hosted page + payment link',free:FREE_PATH,best:'Landing page + analytics + checkout QA',mobile:'Mobile-editable builder and payment dashboard',alt:'Wix, Stripe, Carrd, Framer',q:'landing page builder payment marketing'},
{id:'leadgen',name:'Build a Local Lead Funnel',family:'business_build',goal:'Turn local demand into qualified inquiries.',steps:['Choose service/area','Research demand','Build offer page','Add lead form','Route notifications','Follow up','Measure lead quality'],tools:['Local research','Page builder','Form','CRM','Analytics'],easy:'Page + form + notifications',free:FREE_PATH,best:'Local research + CRM + conversion analytics',mobile:'Mobile CRM and notifications',alt:'HubSpot, Airtable, Google Forms',q:'local lead generation CRM marketing'},
{id:'seo',name:'Create an SEO Content Brief',family:'learn_research',goal:'Produce source-grounded content requirements without pretending rankings are guaranteed.',steps:['Define query intent','Review credible sources','Map subtopics/questions','Draft outline','Add evidence requirements','Write/edit','Measure actual search performance later'],tools:['Search/research','Keyword tools','Writing','Analytics'],easy:'Research → structured outline',free:FREE_PATH,best:'Intent research + evidence + measurement',mobile:'Research and outline on mobile',alt:'Search Console, Ahrefs, Semrush',q:'SEO keyword research content marketing'},
{id:'proposal',name:'Build a Client Proposal',family:'business_build',goal:'Turn discovery notes into a clear proposal and next step.',steps:['Summarize needs','Define scope','Estimate timeline','Write deliverables','Add pricing supplied by owner','Create polished document','Send and track response'],tools:['Notes','Writing','Document/design','E-sign or email'],easy:'Notes → document → send',free:FREE_PATH,best:'Structured scope + polished document + follow-up',mobile:'Document editor + email',alt:'Canva, Google Docs, Notion',q:'proposal document business presentation'},
{id:'checkin',name:'Run a Weekly Client Check-In',family:'fitness_coaching',goal:'Turn client data into a concise coaching adjustment loop.',steps:['Collect adherence and feedback','Review training/nutrition notes','Identify constraints','Decide progression','Update plan','Send summary','Log next checkpoint'],tools:['Form','Spreadsheet/CRM','Programming notes','Messaging'],easy:'Form → review → message',free:FREE_PATH,best:'Structured check-in + history + progression logic',mobile:'Mobile form and messaging',alt:'Airtable, Forms, Notion',q:'fitness client check in coaching programming'},
{id:'sitebrief',name:'Create an Environmental Site Brief',family:'gis_maps',goal:'Assemble public environmental and terrain evidence into a traceable brief.',steps:['Define site boundary','Collect authoritative public layers','Map terrain/hazards','Record source dates','Summarize findings','Export maps','QA citations and limitations'],tools:['Government data','GIS','Mapping','Documents'],easy:'Official layers → map → brief',free:FREE_PATH,best:'Source register + reproducible GIS + QA',mobile:'Review maps mobile; author GIS desktop',alt:'QGIS, ArcGIS, USGS, FEMA',q:'environmental GIS terrain public data mapping'},
{id:'fieldmap',name:'Map a Field Project',family:'gis_maps',goal:'Create a usable field map with source traceability.',steps:['Define area/objective','Select basemap/layers','Add project features','Check coordinates','Design labels/legend','Export field format','Verify on target device'],tools:['GIS','Basemaps','GPS/data collection','Export tools'],easy:'Basemap + project points + export',free:FREE_PATH,best:'Authoritative layers + field validation',mobile:'Use mobile-compatible map export/collection',alt:'QGIS, ArcGIS Field Maps, Google Earth',q:'GIS field mapping GPS map'},
{id:'marketbrief',name:'Build a Market Research Brief',family:'markets',goal:'Organize market data, catalysts and risk without promising a trade outcome.',steps:['Define instrument/timeframe','Collect current market data','Review charts/liquidity','List catalysts','Write bull/bear cases','Define invalidation/risk questions','Archive sources'],tools:['Market data','Charts','News/research','Notes'],easy:'Chart + catalyst list + risk notes',free:FREE_PATH,best:'Multiple sources + explicit uncertainty + archive',mobile:'Charting and notes mobile',alt:'TradingView, public exchange data, finance portals',q:'trading market charts screener risk'},
{id:'localintel',name:'Build a Local Intelligence Brief',family:'local',goal:'Answer a local question using traceable public information.',steps:['Define geography/question','Find official local sources','Collect maps/data','Cross-check dates','Summarize implications','Link sources','Flag unknowns'],tools:['Local government','Public data','Maps','Research notes'],easy:'Official source → map/data → summary',free:FREE_PATH,best:'Cross-source public-data brief',mobile:'Review sources and maps mobile',alt:'Census, county GIS, city open-data portals',q:'local government public data maps'},
{id:'python',name:'Learn Python by Building',family:'learn_research',goal:'Learn coding through a small working project rather than disconnected tutorials.',steps:['Pick a tiny project','Learn only required concepts','Build first version','Debug','Add one feature','Explain what changed','Repeat'],tools:['Course/reference','Code editor','AI tutor','Version control'],easy:'Tutorial + tiny project',free:FREE_PATH,best:'Project loop + docs + version control',mobile:'Use mobile lessons; code on desktop when practical',alt:'freeCodeCamp, Real Python, Kaggle Learn',q:'learn Python coding tutorial course'},
{id:'docs',name:'Process a Document Intake',family:'general',goal:'Convert incoming documents into searchable, checked information.',steps:['Collect files','OCR if needed','Extract key fields','Validate against source','Organize output','Flag uncertain values','Archive provenance'],tools:['PDF','OCR','Spreadsheet/database','QA checklist'],easy:'PDF/OCR → structured notes',free:FREE_PATH,best:'Extraction + human-readable provenance + QA',mobile:'Capture/scan mobile; QA larger screen',alt:'OCR tools, PDF editors, spreadsheets',q:'OCR PDF extract text document'}
];
const PLAYBOOKS=[
{id:'deep-research',cat:'Research',title:'Source-Grounded Deep Research',best:'Questions where accuracy and provenance matter.',prompt:'Define the decision or question. Find primary/official sources first. Separate observed facts, inference, and unknowns. Cross-check material claims. Return: answer, evidence table, contradictions, confidence, and next verification step.',q:'research academic evidence official sources'},
{id:'site-audit',cat:'Business',title:'Website Conversion Audit',best:'Improving clarity, trust and conversion without fake metrics.',prompt:'Review the site as a first-time mobile visitor. Score clarity, navigation, trust, offer, friction, accessibility and speed. For each issue give evidence, impact, exact fix, and test. Do not invent traffic, rankings or conversion rates.',q:'website analytics accessibility performance'},
{id:'reel-script',cat:'Creator',title:'60-Second Reel Builder',best:'Turning one idea into a tight vertical video.',prompt:'Create a 60-second vertical-video plan: 0-3s hook, 3-15s context, 15-45s value, 45-55s proof/example, 55-60s CTA. Include on-screen text, shot changes and edit notes. Keep every line useful.',q:'short social video editor voice'},
{id:'agent-spec',cat:'AI',title:'Reliable Agent Specification',best:'Building an agent that uses tools safely.',prompt:'Define goal, inputs, allowed tools, permissions, routing rules, failure states, confirmation boundaries, logging, tests and rollback. Prefer explicit tool schemas and observable outcomes over vague autonomy.',q:'AI agent automation workflow'},
{id:'client-intake',cat:'Fitness',title:'Fitness Client Intake to Program',best:'Turning intake data into a defensible coaching plan.',prompt:'Organize goals, training history, schedule, equipment, preferences, constraints and readiness. Identify unknowns before programming. Build session structure, progression rules, adherence checkpoints and review cadence.',q:'fitness coaching client intake programming'},
{id:'grant-screen',cat:'Grants',title:'Grant Eligibility Screen',best:'Deciding whether an opportunity deserves work.',prompt:'Use the official notice. Extract applicant eligibility, geography, eligible activities, match requirements, deadlines, scoring criteria and required attachments. Mark every field confirmed, uncertain or not found. End with pursue / investigate / do not pursue and why.',q:'grant funding research official'},
{id:'gis-brief',cat:'GIS',title:'GIS Evidence Brief',best:'Turning spatial data into a traceable decision brief.',prompt:'Define boundary and question. Use authoritative layers where possible. Record source, date, coordinate system and limitations. Build map outputs, summarize spatial findings, distinguish absence of data from absence of risk, and cite every consequential layer.',q:'GIS geospatial mapping public data'},
{id:'market-risk',cat:'Markets',title:'Market Scenario & Risk Brief',best:'Structuring market research without pretending certainty.',prompt:'State instrument and timeframe. Separate current observations from interpretation. Build bull, bear and neutral scenarios, catalysts, invalidation conditions and risk questions. Do not claim a guaranteed direction or fabricated probability.',q:'trading market charts risk'},
{id:'local-brief',cat:'Local',title:'Local Intelligence Brief',best:'Local business, government or community questions.',prompt:'Define exact geography. Prefer city/county/state/official sources, then reputable local reporting. Check dates and boundaries. Return what is known, what changed, map/data links, practical implication and unresolved questions.',q:'local government public data maps'},
{id:'learn-plan',cat:'Learn',title:'Learn by Building',best:'Learning technical topics without passive tutorial overload.',prompt:'Pick one practical project. Break it into skills needed now, not a full curriculum. For each step: concept, tiny exercise, project application, check-for-understanding, common failure, next increment.',q:'tutorial course Python coding'},
{id:'proposal',cat:'Business',title:'Client Proposal Builder',best:'Turning discovery into a concise business proposal.',prompt:'From supplied discovery notes only, write: problem, desired outcome, scope, deliverables, assumptions, timeline, responsibilities, owner-supplied pricing, exclusions and next step. Never invent client facts or commercial results.',q:'business proposal document presentation'},
{id:'qa',cat:'Utility',title:'Production QA Red-Team',best:'Checking a shipped website or workflow before calling it done.',prompt:'Test happy paths, bad inputs, empty states, mobile layouts, keyboard navigation, external links, same-origin requests, JS errors, analytics events and accessibility. Record reproducible failures, fix them, then rerun the same test before certifying.',q:'website testing accessibility performance'}
];
function page(id,kicker,title,desc,body){return `<section class="view" id="view-${id}"><div class="atlas-plus-hero"><div class="eyebrow">${kicker}</div><h1>${title}</h1><p>${desc}</p></div>${body}<div class="feedbackbar" data-feedback-scope="${id}"><strong>Was this useful?</strong><button class="btn outline" data-feedback="yes">Yes</button><button class="btn outline" data-feedback="no">No</button><div class="unmet"><input aria-label="Tell Atlas what you could not find" placeholder="I couldn’t find what I needed…"><button class="btn blue" data-unmet>Send</button></div><span class="micro">Feedback can improve discovery. It never changes verification, access labels, or paid/organic treatment.</span></div></section>`}
function cards(items,source){return `<div class="atlas-plus-grid">${items.map(([n,d,q])=>`<button class="atlas-plus-card" data-q="${q||n}" data-source="${source}" data-family="${familyFrom(q||n)}"><h3>${n}</h3>${d?`<p>${d}</p>`:''}</button>`).join('')}</div>`}
function stackHTML(s){return `<article class="stack" data-stack-id="${s.id}"><div class="eyebrow" style="color:#175cd3">Complete workflow</div><h3>${s.name}</h3><p class="stack-goal">${s.goal}</p><ol class="stack-steps">${s.steps.map(x=>`<li>${x}</li>`).join('')}</ol><div class="stack-tools">${s.tools.map(x=>`<span>${x}</span>`).join('')}</div><div class="choice-grid"><div class="choice"><b>Easiest</b>${s.easy}</div><div class="choice"><b>Free path</b>${s.free}</div><div class="choice"><b>Best overall</b>${s.best}</div><div class="choice"><b>Mobile-friendly</b>${s.mobile}</div></div><p class="micro"><b>Alternatives:</b> ${s.alt}. These are workflow roles/examples, not pricing or ranking claims. Atlas’s audited metadata remains authoritative.</p><button class="btn soft" data-stack-search="${s.q}" data-stack="${s.name}" data-family="${s.family}">Find tools for this Stack</button></article>`}
function playbookHTML(p){return `<article class="playbook" data-playbook-id="${p.id}" data-cat="${p.cat.toLowerCase()}" data-search="${(p.title+' '+p.best).toLowerCase()}"><div class="playbook-meta"><span>${p.cat}</span><span>Reusable</span></div><h3>${p.title}</h3><p class="micro">${p.best}</p><pre>${p.prompt}</pre><div class="actions"><button class="btn outline" data-copy-playbook="${p.id}">Copy playbook</button><button class="btn soft" data-playbook-search="${p.q}" data-playbook="${p.title}">Find supporting tools</button></div></article>`}
function renderPlaybooks(){const grid=$('#playbookGrid');if(!grid)return;const term=($('#playbookSearch')?.value||'').toLowerCase().trim(),cat=$('#playbookCat')?.value||'';const rows=PLAYBOOKS.filter(p=>(!term||(p.title+' '+p.best+' '+p.prompt).toLowerCase().includes(term))&&(!cat||p.cat===cat));grid.innerHTML=rows.length?rows.map(playbookHTML).join(''):'<div class="empty">No playbooks match those filters.</div>';$('#playbookCount').textContent=`${rows.length} playbooks`;}
function inject(){style();const main=$('#main');if(!main)return;
 const doPage=page('do','DO','Accomplish something','Start from the outcome. Atlas routes into the existing task-ranked library instead of forcing you to know a tool name.',cards(DO,'do'));
 const learnPage=page('learn','LEARN','Learn something','Find tutorials, courses, reference material and research by subject.',cards(LEARN.map(([n,q])=>[n,'',q]),'learn'));
 const exploreBody=`<div class="sectionhead"><div><h2>Explore by mood</h2><p>Useful discovery for when you do not know what you want yet.</p></div><button class="btn blue" id="surprisePlus">Surprise Me</button></div>${cards(EXPLORE.map(([n,q])=>[n,'',q]),'explore')}`;
 const explorePage=page('explore','EXPLORE','Discover something useful','Bored, curious, or looking for something unexpected? Use a mood or let Atlas choose.',exploreBody);
 const evidence=`<div class="evidence-note"><b>Behavior-assisted ranking is not active yet.</b>Current production attribution has not crossed the evidence threshold. Atlas will collect task family, result position and result interactions first. Verification/access rules always outrank behavior signals.</div>`;
 const stacksPage=page('stacks','STACKS',`${STACKS.length} complete workflows, not isolated tools`,'Each Stack starts with a goal and shows sequence, easiest path, audited-free path, best-overall workflow shape, mobile path and alternatives.',`<div class="atlas-plus-grid two">${STACKS.map(stackHTML).join('')}</div>`);
 const cats=[...new Set(PLAYBOOKS.map(p=>p.cat))];
 const playbooksPage=page('playbooks','PLAYBOOK LIBRARY','Reusable decision and execution playbooks','Copy a proven structure, then use Atlas to find the tools that support it.',`<div class="filterline"><input id="playbookSearch" type="search" placeholder="Search playbooks…" aria-label="Search playbooks"><select id="playbookCat" aria-label="Filter playbook category"><option value="">All categories</option>${cats.map(c=>`<option>${c}</option>`).join('')}</select><span class="micro" id="playbookCount"></span></div><div class="atlas-plus-grid" id="playbookGrid"></div>`);
 main.insertAdjacentHTML('beforeend',doPage+learnPage+explorePage+stacksPage+playbooksPage);
 const items=[['do','Do'],['learn','Learn'],['stacks','Stacks'],['playbooks','Playbooks'],['explore','Explore']];
 const nav=$('.navlinks');if(nav)items.slice().reverse().forEach(([id,label])=>{const b=document.createElement('button');b.className='navbtn atlas-plus-nav';b.dataset.plusView=id;b.textContent=label;nav.prepend(b)});
 const mobile=$('#mobileNav');if(mobile)items.slice().reverse().forEach(([id,label])=>{const b=document.createElement('button');b.className='navbtn';b.dataset.plusView=id;b.textContent=label;mobile.prepend(b)});
 renderPlaybooks();$('#playbookSearch')?.addEventListener('input',renderPlaybooks);$('#playbookCat')?.addEventListener('change',renderPlaybooks);
 document.addEventListener('click',async e=>{
  const pv=e.target.closest('[data-plus-view]');if(pv){openPlus(pv.dataset.plusView);return}
  const c=e.target.closest('[data-q]');if(c){capture('atlas_intent_submitted',{surface:c.dataset.source||'discovery',task_family:c.dataset.family||familyFrom(c.dataset.q)});search(c.dataset.q,{source:c.dataset.source,task_family:c.dataset.family});return}
  const ss=e.target.closest('[data-stack-search]');if(ss){capture('atlas_stack_opened',{stack:ss.dataset.stack,task_family:ss.dataset.family});search(ss.dataset.stackSearch,{source:'stack',task_family:ss.dataset.family});return}
  const ps=e.target.closest('[data-playbook-search]');if(ps){capture('atlas_playbook_opened',{playbook:ps.dataset.playbook,action:'supporting_tools'});search(ps.dataset.playbookSearch,{source:'playbook'});return}
  const cp=e.target.closest('[data-copy-playbook]');if(cp){const p=PLAYBOOKS.find(x=>x.id===cp.dataset.copyPlaybook);if(!p)return;try{await navigator.clipboard.writeText(p.prompt);cp.textContent='Copied';capture('atlas_playbook_copied',{playbook:p.title,category:p.cat})}catch(_){cp.textContent='Copy failed'}return}
  const f=e.target.closest('[data-feedback]');if(f){const scope=f.closest('[data-feedback-scope]')?.dataset.feedbackScope||'unknown';capture('atlas_feedback',{value:f.dataset.feedback,scope});f.closest('.feedbackbar').querySelector('strong').textContent='Thanks — feedback recorded.';return}
  const u=e.target.closest('[data-unmet]');if(u){const bar=u.closest('.feedbackbar'),input=bar.querySelector('input'),value=input.value.trim();if(!value)return;capture('atlas_unmet_request',{scope:bar.dataset.feedbackScope,length:value.length,task_family:familyFrom(value)});input.value='';bar.querySelector('strong').textContent='Request recorded.';return}
  const tool=e.target.closest('[data-tool-visit]');if(tool){const card=tool.closest('.tool'),cards=$$('#toolGrid .tool'),rank=card?cards.indexOf(card)+1:0;capture('atlas_outbound_click',{tool_id:tool.dataset.toolId||'',tool_name:tool.dataset.toolName||card?.querySelector('h3')?.textContent?.trim()||'',domain:tool.dataset.toolDomain||'',rank_position:rank||null,verification:tool.dataset.toolVerification||''});return}
  const detail=e.target.closest('button[onclick^="openDetail"]');if(detail){const card=detail.closest('.tool'),rank=card?$$('#toolGrid .tool').indexOf(card)+1:0;capture('atlas_result_opened',{tool_name:card?.querySelector('h3')?.textContent?.trim()||'',rank_position:rank||null});return}
  const fav=e.target.closest('.fav');if(fav){const card=fav.closest('.tool');capture('atlas_saved',{tool_name:card?.querySelector('h3')?.textContent?.trim()||''});}
 });
 $('#surprisePlus')?.addEventListener('click',()=>{const picks=[['live nature animal cams','watch_listen'],['NASA space science streams','watch_listen'],['interactive maps earth','gis_maps'],['visual interactive experiments','general'],['free legal documentaries streaming','watch_listen'],['weird useful websites','general'],['free browser games','general'],['learn something random tutorial','learn_research']];const [q,f]=picks[Math.floor(Math.random()*picks.length)];capture('atlas_surprise_used',{task_family:f});search(q,{source:'surprise',task_family:f})});
 const watchBtn=$('[data-view="watch"]');watchBtn?.addEventListener('click',()=>capture('atlas_watch_opened',{}),true);
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#mobileNav')?.classList.contains('open')){$('#mobileNav').classList.remove('open');$('#menuBtn')?.setAttribute('aria-expanded','false')}});
 window.Atlas.restoreRoute();
 capture('atlas_discovery_loaded',{stack_count:STACKS.length,playbook_count:PLAYBOOKS.length,behavior_ranking_active:BEHAVIOR_POLICY.enabled});
}
if(window.Atlas)inject();else document.addEventListener('atlas:ready',inject,{once:true});
})();