const { chromium } = require('playwright');
const fs = require('fs');
const URL = process.env.ATLAS_URL || 'https://2strongtrainers-art.github.io/terrain-environmental-gis/atlas/';
const report = { url: URL, started_at: new Date().toISOString(), tests: [], console_errors: [], page_errors: [], request_failures: [] };
function log(name, ok, detail=''){ report.tests.push({name,ok,detail}); console.log(`${ok?'PASS':'FAIL'} | ${name}${detail?' | '+detail:''}`); }
async function run(name,fn){ try{ const d=await fn(); log(name,true,d||''); }catch(e){ log(name,false,e?.message||String(e)); } }
function assert(c,m){ if(!c) throw new Error(m); }
async function activeView(page,name){ return page.locator(`#view-${name}`).evaluate(el=>el.classList.contains('active')); }
async function countFrom(page,sel){ const t=await page.locator(sel).innerText(); return Number((t.match(/[\d,]+/)||['0'])[0].replace(/,/g,'')); }
async function clearFilters(page){ await page.locator('#clearFilters').click(); await page.waitForTimeout(100); }
async function openLibrary(page){ await page.locator('.navlinks button[data-view="library"]').click(); await page.waitForTimeout(80); }
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||"/usr/bin/google-chrome",args:["--no-sandbox"]});
 try{
  const context=await browser.newContext({viewport:{width:1440,height:1050}});
  const page=await context.newPage();
  page.on('console',m=>{if(m.type()==='error')report.console_errors.push(m.text())});
  page.on('pageerror',e=>report.page_errors.push(String(e)));
  page.on('requestfailed',r=>{const u=r.url();if(u.startsWith(URL)||u.includes('2strongtrainers-art.github.io'))report.request_failures.push(`${u} :: ${r.failure()?.errorText||'failed'}`)});
  await context.addInitScript(()=>localStorage.clear());
  await run('Live production page responds and initializes',async()=>{const r=await page.goto(URL,{waitUntil:'networkidle',timeout:60000});assert(r&&r.status()===200,`HTTP ${r?r.status():'no response'}`);await page.waitForFunction(()=>document.querySelector('#statIndexed')?.textContent?.includes('1,834'),null,{timeout:30000});assert((await page.title()).includes('Nick’s Digital Atlas'),'Unexpected title');assert(await page.locator('text=Atlas data could not load.').count()===0,'Fatal Atlas data banner shown');return `HTTP ${r.status()}, title loaded, 1,834 index initialized`;});
  await run('Production data counts',async()=>{const a=await page.locator('#statIndexed').innerText(),b=await page.locator('#statSource').innerText(),c=await page.locator('#statVerified').innerText();assert(a==='1,834',`indexed=${a}`);assert(b==='1,802',`source=${b}`);assert(c==='1,529',`verified=${c}`);return `indexed=${a}; source=${b}; live=${c}`;});
  await run('Desktop primary navigation: all six views',async()=>{for(const v of ['home','library','categories','free','archive','quality']){await page.locator(`.navlinks button[data-view="${v}"]`).click();assert(await activeView(page,v),`${v} did not activate`);assert(page.url().endsWith(`#${v}`),`hash not updated for ${v}`)}return 'Home, Library, Categories, Free, Power User, Data Quality';});
  await run('Home CTA: Search the library',async()=>{await page.locator('.navlinks button[data-view="home"]').click();await page.locator('button:has-text("Browse all 1,834 tools")').click();assert(await activeView(page,'library'),'Library did not open');return 'CTA opens Master Library';});
  await run('Home CTA: New here focus behavior',async()=>{await page.locator('.navlinks button[data-view="home"]').click();await page.locator('#jumpCommand').click();await page.waitForTimeout(450);assert(await page.locator('#commandInput').evaluate(el=>document.activeElement===el),'Command input not focused');return 'scroll/focus target works';});
  await run('Family Command Center: empty input guidance',async()=>{await page.locator('#commandInput').fill('');await page.locator('#routeBtn').click();const t=await page.locator('#routeSuggestions').innerText();assert(t.includes('Tell me the outcome'),`Unexpected guidance: ${t}`);return 'empty state guidance rendered';});
  await run('Family Command Center: button route',async()=>{await page.locator('#commandInput').fill('make a video');await page.locator('#routeBtn').click();const s=page.locator('#routeSuggestions button[data-route]');assert(await s.count()>0,'No route suggestions');await s.first().click();assert(await activeView(page,'library'),'Route did not open library');assert(await countFrom(page,'#resultCount')>0,'Route produced zero results');return `results=${await page.locator('#resultCount').innerText()}`;});
  await run('Family Command Center: Enter key route',async()=>{await page.locator('.navlinks button[data-view="home"]').click();await page.locator('#commandInput').fill('research science');await page.locator('#commandInput').press('Enter');assert(await page.locator('#routeSuggestions button[data-route]').count()>0,'Enter did not create suggestions');return 'Enter invokes router';});
  await run('Goal-first cards: all eight routes click through',async()=>{for(const g of ['video','research','design','business','automation','maps','no-login','recommended']){await page.locator('.navlinks button[data-view="home"]').click();await page.locator(`#goalGrid [data-goal="${g}"]`).click();if(g==='no-login'){assert(await activeView(page,'free'),`${g} did not open free view`);assert(await page.locator('#freeGrid .tool').count()>0,'Free view empty')}else{assert(await activeView(page,'library'),`${g} did not open library`);assert(await countFrom(page,'#resultCount')>0,`${g} produced zero results`)}}return 'video, research, design, business, automation, maps, no-login, recommended';});
  await run('Friend Mode card',async()=>{await page.locator('.navlinks button[data-view="home"]').click();await page.locator('#friendMode').click();await page.waitForTimeout(150);assert(await activeView(page,'home'),'Friend Mode left home');assert(await page.locator('#commandInput').evaluate(el=>document.activeElement===el),'Friend Mode did not focus input');return 'focuses beginner command input';});
  await run('Experience cards: Browse by goal and Power User',async()=>{await page.locator('#view-home .card.click[data-view="categories"]').click();assert(await activeView(page,'categories'),'Browse by goal failed');await page.locator('.navlinks button[data-view="home"]').click();await page.locator('#view-home .card.click[data-view="archive"]').click();assert(await activeView(page,'archive'),'Power User card failed');return 'both experience cards navigate';});
  await run('Master Library default state and pagination',async()=>{await openLibrary(page);await clearFilters(page);assert(await countFrom(page,'#resultCount')===1834,`count=${await page.locator('#resultCount').innerText()}`);assert(await page.locator('#toolGrid .tool').count()===60,`page cards=${await page.locator('#toolGrid .tool').count()}`);const n=page.locator('#pagination button:has-text("Next")');assert(await n.isEnabled(),'Next disabled on page 1');await n.click();assert((await page.locator('#pagination').innerText()).includes('Page 2 of'),'Did not reach page 2');await page.locator('#pagination button:has-text("Previous")').click();assert((await page.locator('#pagination').innerText()).includes('Page 1 of'),'Did not return page 1');return '1,834 results; 60/page; Next/Previous work';});
  await run('Library search control',async()=>{await clearFilters(page);await page.locator('#searchInput').fill('Genspark');await page.waitForTimeout(120);assert(await countFrom(page,'#resultCount')>0,'No Genspark results');assert((await page.locator('#toolGrid').innerText()).toLowerCase().includes('genspark'),'Genspark not in cards');return await page.locator('#resultCount').innerText();});
  await run('Source filter control',async()=>{await clearFilters(page);await page.locator('#sourceFilter').selectOption({label:'AI'});await page.waitForTimeout(80);assert(await countFrom(page,'#resultCount')>0,'AI source returned zero');return await page.locator('#resultCount').innerText();});
  await run('Pricing filter control',async()=>{await clearFilters(page);const vals=await page.locator('#pricingFilter option').evaluateAll(o=>o.map(x=>x.value).filter(Boolean));assert(vals.length>0,'No pricing options');await page.locator('#pricingFilter').selectOption(vals[0]);await page.waitForTimeout(80);assert(await countFrom(page,'#resultCount')>0,`Pricing ${vals[0]} returned zero`);return `${vals[0]} -> ${await page.locator('#resultCount').innerText()}`;});
  await run('Verification filter controls',async()=>{await clearFilters(page);await page.locator('#verificationFilter').selectOption('Live verified');await page.waitForTimeout(80);assert(await countFrom(page,'#resultCount')===1529,`live count=${await page.locator('#resultCount').innerText()}`);await page.locator('#verificationFilter').selectOption('not-live');await page.waitForTimeout(80);assert(await countFrom(page,'#resultCount')===305,`not-live count=${await page.locator('#resultCount').innerText()}`);return 'Live verified=1,529; not-live=305';});
  await run('Priority filter control',async()=>{await clearFilters(page);await page.locator('#priorityFilter').selectOption('High');await page.waitForTimeout(80);assert(await countFrom(page,'#resultCount')>0,'High priority returned zero');return await page.locator('#resultCount').innerText();});
  await run('Sort control: A–Z, verified first, priority first',async()=>{await clearFilters(page);await page.locator('#sortFilter').selectOption('az');await page.waitForTimeout(80);let n=await page.locator('#toolGrid .tool h3').allInnerTexts();assert(n.length>1&&n[0].localeCompare(n[1])<=0,'A–Z ordering failed');await page.locator('#sortFilter').selectOption('verified');await page.waitForTimeout(80);assert((await page.locator('#toolGrid .tool').first().innerText()).includes('Live verified'),'Verified-first failed');await page.locator('#sortFilter').selectOption('priority');await page.waitForTimeout(80);assert(await page.locator('#toolGrid .tool').count()>0,'Priority sort empty');return 'all sort modes execute';});
  await run('Clear filters control',async()=>{await page.locator('#searchInput').fill('video');await page.locator('#priorityFilter').selectOption('High');await page.locator('#clearFilters').click();await page.waitForTimeout(80);assert(await page.locator('#searchInput').inputValue()==='','Search not cleared');assert(await page.locator('#priorityFilter').inputValue()==='','Priority not cleared');assert(await countFrom(page,'#resultCount')===1834,'Full count not restored');return 'restores clean 1,834-result state';});
  await run('Favorites: add, favorites-only, remove',async()=>{await clearFilters(page);await page.locator('#toolGrid .tool .fav').first().click();await page.locator('#favOnly').click();await page.waitForTimeout(80);assert(await countFrom(page,'#resultCount')===1,`favorites count=${await page.locator('#resultCount').innerText()}`);assert(await page.locator('#favOnly').evaluate(el=>el.classList.contains('active')),'Favorite-only chip not active');await page.locator('#toolGrid .tool .fav').first().click();await page.waitForTimeout(80);assert(await countFrom(page,'#resultCount')===0,'Removing favorite did not update filtered list');await page.locator('#favOnly').click();await clearFilters(page);return 'add/filter/remove state works';});
  await run('Tool details modal: open and close button',async()=>{await clearFilters(page);const n=await page.locator('#toolGrid .tool h3').first().innerText();await page.locator('#toolGrid .tool button:has-text("Details")').first().click();assert(await page.locator('#detailModal').evaluate(el=>el.classList.contains('open')),'Modal not open');assert((await page.locator('#detailTitle').innerText())===n,'Modal title mismatch');await page.locator('#modalClose').click();assert(!(await page.locator('#detailModal').evaluate(el=>el.classList.contains('open'))),'Modal did not close');return n;});
  await run('Tool details modal: Escape and backdrop close',async()=>{await page.locator('#toolGrid .tool button:has-text("Details")').first().click();await page.keyboard.press('Escape');assert(!(await page.locator('#detailModal').evaluate(el=>el.classList.contains('open'))),'Escape failed');await page.locator('#toolGrid .tool button:has-text("Details")').first().click();await page.locator('#detailModal').click({position:{x:3,y:3}});assert(!(await page.locator('#detailModal').evaluate(el=>el.classList.contains('open'))),'Backdrop failed');return 'Escape and backdrop both close';});
  await run('Tool external Visit link opens a new tab',async()=>{await page.locator('#searchInput').fill('Genspark');await page.waitForTimeout(100);const l=page.locator('#toolGrid .tool a:has-text("Visit")').first(),href=await l.getAttribute('href');assert(/^https?:\/\//.test(href||''),`Bad href: ${href}`);assert((await l.getAttribute('target'))==='_blank','Visit link not target=_blank');const [popup]=await Promise.all([page.waitForEvent('popup',{timeout:10000}),l.click()]);await popup.waitForTimeout(300);assert(popup.url()!=='about:blank','Popup did not navigate');await popup.close();return href;});
  await run('Categories render and each category card routes',async()=>{for(const cat of ['AI','Design & Creative','Gaming','Education & Learning','Curated Library']){await page.locator('.navlinks button[data-view="categories"]').click();const c=page.locator(`#categoryGrid [data-cat="${cat}"]`);assert(await c.count()===1,`Missing category ${cat}`);await c.click();assert(await activeView(page,'library'),`${cat} did not open library`);assert(await page.locator('#sourceFilter').inputValue()===cat,`${cat} filter mismatch`);assert(await countFrom(page,'#resultCount')>0,`${cat} returned zero`)}return 'all source categories route';});
  await run('Free / No Login collection',async()=>{await page.locator('.navlinks button[data-view="free"]').click();const n=await page.locator('#freeGrid .tool').count();assert(n===4,`expected 4 explicit access audits, got ${n}`);await page.locator('#freeGrid .tool button:has-text("Details")').first().click();assert(await page.locator('#detailModal').evaluate(el=>el.classList.contains('open')),'Free item detail failed');await page.locator('#modalClose').click();return '4 explicitly audited tools; details work';});
  await run('Power User archive: four source cards and browse actions',async()=>{for(const source of ['AI','Design & Creative','Gaming','Education & Learning']){await page.locator('.navlinks button[data-view="archive"]').click();assert(await page.locator('#archiveGrid .sourcecard').count()===4,'Expected four source cards');const c=page.locator(`#archiveGrid .sourcecard:has-text("${source}")`).first(),a=c.locator('a:has-text("Open source")');assert(/^https:\/\/docs\.google\.com\//.test((await a.getAttribute('href'))||''),`Bad source href for ${source}`);await c.locator('button:has-text("Browse in Atlas")').click();assert(await activeView(page,'library'),`Browse ${source} failed`);assert(await page.locator('#sourceFilter').inputValue()===source,`${source} filter not applied`)}return 'all four source cards route correctly';});
  await run('Power User: Review non-live-verified records',async()=>{await clearFilters(page);await page.locator('.navlinks button[data-view="archive"]').click();await page.locator('#browseRaw').click();assert(await activeView(page,'library'),'Browse all did not open library');assert(await page.locator('#verificationFilter').inputValue()==='not-live','not-live filter not applied');assert(await countFrom(page,'#resultCount')===305,`count=${await page.locator('#resultCount').innerText()}`);return '305 non-live-verified source-indexed records';});
  await run('Data Quality snapshot',async()=>{await page.locator('.navlinks button[data-view="quality"]').click();const v=await Promise.all(['qIndexed','qSource','qVerified','qAccess','qDate'].map(id=>page.locator('#'+id).innerText()));assert(v[0]==='1,834'&&v[1]==='1,802'&&v[2]==='1,529'&&v[3]==='4'&&v[4]==='2026-09-03',`Unexpected: ${v.join('|')}`);return v.join(' / ');});
  await run('Direct hash routing',async()=>{await page.goto(URL+'#quality',{waitUntil:'networkidle',timeout:60000});await page.waitForFunction(()=>document.querySelector('#view-quality')?.classList.contains('active'));assert(await activeView(page,'quality'),'#quality route not active');return '#quality opens Data Quality directly';});
  await run('Desktop layout has no horizontal overflow',async()=>{const d=await page.evaluate(()=>({sw:document.documentElement.scrollWidth,cw:document.documentElement.clientWidth}));assert(d.sw<=d.cw+1,`scrollWidth ${d.sw} > clientWidth ${d.cw}`);return `${d.sw}px / ${d.cw}px`;});
  fs.mkdirSync('qa-artifacts',{recursive:true});await page.goto(URL,{waitUntil:'networkidle',timeout:60000});await page.waitForFunction(()=>document.querySelector('#statIndexed')?.textContent?.includes('1,834'));await page.screenshot({path:'qa-artifacts/atlas-desktop-home.png',fullPage:true});await openLibrary(page);await page.locator('#searchInput').fill('video');await page.waitForTimeout(100);await page.screenshot({path:'qa-artifacts/atlas-desktop-library.png',fullPage:true});await context.close();
  const mctx=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:2});const mobile=await mctx.newPage();mobile.on('console',m=>{if(m.type()==='error')report.console_errors.push('MOBILE: '+m.text())});mobile.on('pageerror',e=>report.page_errors.push('MOBILE: '+String(e)));await mctx.addInitScript(()=>localStorage.clear());await mobile.goto(URL,{waitUntil:'networkidle',timeout:60000});await mobile.waitForFunction(()=>document.querySelector('#statIndexed')?.textContent?.includes('1,834'));
  await run('Mobile layout has no horizontal overflow',async()=>{const d=await mobile.evaluate(()=>({sw:document.documentElement.scrollWidth,cw:document.documentElement.clientWidth}));assert(d.sw<=d.cw+1,`scrollWidth ${d.sw} > clientWidth ${d.cw}`);return `${d.sw}px / ${d.cw}px`;});
  await run('Mobile menu opens and all six nav controls work',async()=>{assert(await mobile.locator('#menuBtn').isVisible(),'Mobile Menu button not visible');for(const v of ['home','library','categories','free','archive','quality']){await mobile.locator('#menuBtn').click();assert((await mobile.locator('#menuBtn').getAttribute('aria-expanded'))==='true',`Menu did not expand for ${v}`);await mobile.locator(`#mobileNav button[data-view="${v}"]`).click();assert(await activeView(mobile,v),`${v} did not activate on mobile`);assert((await mobile.locator('#menuBtn').getAttribute('aria-expanded'))==='false',`Menu did not close after ${v}`)}return 'menu + six mobile navigation controls';});
  await run('Mobile search and details modal',async()=>{await mobile.locator('#menuBtn').click();await mobile.locator('#mobileNav button[data-view="library"]').click();await mobile.locator('#searchInput').fill('Genspark');await mobile.waitForTimeout(100);assert(await countFrom(mobile,'#resultCount')>0,'Mobile search returned zero');await mobile.locator('#toolGrid .tool button:has-text("Details")').first().click();assert(await mobile.locator('#detailModal').evaluate(el=>el.classList.contains('open')),'Mobile details did not open');const d=await mobile.locator('.modalbox').evaluate(el=>({left:el.getBoundingClientRect().left,right:el.getBoundingClientRect().right,w:window.innerWidth}));assert(d.left>=-1&&d.right<=d.w+1,`Modal overflow: ${JSON.stringify(d)}`);await mobile.locator('#modalClose').click();return 'search + modal fit within 390px viewport';});
  await mobile.goto(URL,{waitUntil:'networkidle',timeout:60000});await mobile.waitForFunction(()=>document.querySelector('#statIndexed')?.textContent?.includes('1,834'));await mobile.screenshot({path:'qa-artifacts/atlas-mobile-home.png',fullPage:true});await mctx.close();
  await run('No production JavaScript page errors',async()=>{assert(report.page_errors.length===0,report.page_errors.join(' | '));return '0 page errors';});
  await run('No same-origin request failures during QA',async()=>{assert(report.request_failures.length===0,report.request_failures.join(' | '));return '0 Atlas-origin request failures';});
  const failures=report.tests.filter(t=>!t.ok);report.finished_at=new Date().toISOString();report.passed=report.tests.length-failures.length;report.failed=failures.length;fs.writeFileSync('qa-artifacts/atlas-live-qa-report.json',JSON.stringify(report,null,2));fs.writeFileSync('qa-artifacts/atlas-live-qa-summary.txt',[`Nick's Digital Atlas Live Chromium QA`,`URL: ${URL}`,`Passed: ${report.passed}`,`Failed: ${report.failed}`,`Console errors: ${report.console_errors.length}`,`Page errors: ${report.page_errors.length}`,`Same-origin request failures: ${report.request_failures.length}`,'',...report.tests.map(t=>`${t.ok?'PASS':'FAIL'} | ${t.name}${t.detail?' | '+t.detail:''}`)].join('\n'));console.log(`\nQA_TOTAL=${report.tests.length} QA_PASSED=${report.passed} QA_FAILED=${report.failed}`);if(report.console_errors.length)console.log('CONSOLE_ERRORS='+JSON.stringify(report.console_errors));if(failures.length)process.exitCode=1;
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exit(1)});